// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalAuthorCodeDao is internal type for wrapping internal DAO implements.
type internalAuthorCodeDao = *internal.AuthorCodeDao

// authorCodeDao is the data access object for table author_code.
// You can define custom methods on it to extend its functionality as you wish.
type authorCodeDao struct {
	internalAuthorCodeDao
}

var (
	// AuthorCode is globally public accessible object for table author_code operations.
	AuthorCode = authorCodeDao{
		internal.NewAuthorCodeDao(),
	}
)

// Fill with you ideas below.
