// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalAuthorIncomeDao is internal type for wrapping internal DAO implements.
type internalAuthorIncomeDao = *internal.AuthorIncomeDao

// authorIncomeDao is the data access object for table author_income.
// You can define custom methods on it to extend its functionality as you wish.
type authorIncomeDao struct {
	internalAuthorIncomeDao
}

var (
	// AuthorIncome is globally public accessible object for table author_income operations.
	AuthorIncome = authorIncomeDao{
		internal.NewAuthorIncomeDao(),
	}
)

// Fill with you ideas below.
