// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalAuthorInfoDao is internal type for wrapping internal DAO implements.
type internalAuthorInfoDao = *internal.AuthorInfoDao

// authorInfoDao is the data access object for table author_info.
// You can define custom methods on it to extend its functionality as you wish.
type authorInfoDao struct {
	internalAuthorInfoDao
}

var (
	// AuthorInfo is globally public accessible object for table author_info operations.
	AuthorInfo = authorInfoDao{
		internal.NewAuthorInfoDao(),
	}
)

// Fill with you ideas below.
