// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalAuthorIncomeDetailDao is internal type for wrapping internal DAO implements.
type internalAuthorIncomeDetailDao = *internal.AuthorIncomeDetailDao

// authorIncomeDetailDao is the data access object for table author_income_detail.
// You can define custom methods on it to extend its functionality as you wish.
type authorIncomeDetailDao struct {
	internalAuthorIncomeDetailDao
}

var (
	// AuthorIncomeDetail is globally public accessible object for table author_income_detail operations.
	AuthorIncomeDetail = authorIncomeDetailDao{
		internal.NewAuthorIncomeDetailDao(),
	}
)

// Fill with you ideas below.
