// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalBookCommentReplyDao is internal type for wrapping internal DAO implements.
type internalBookCommentReplyDao = *internal.BookCommentReplyDao

// bookCommentReplyDao is the data access object for table book_comment_reply.
// You can define custom methods on it to extend its functionality as you wish.
type bookCommentReplyDao struct {
	internalBookCommentReplyDao
}

var (
	// BookCommentReply is globally public accessible object for table book_comment_reply operations.
	BookCommentReply = bookCommentReplyDao{
		internal.NewBookCommentReplyDao(),
	}
)

// Fill with you ideas below.
