// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalBookCommentCopy1Dao is internal type for wrapping internal DAO implements.
type internalBookCommentCopy1Dao = *internal.BookCommentCopy1Dao

// bookCommentCopy1Dao is the data access object for table book_comment_copy1.
// You can define custom methods on it to extend its functionality as you wish.
type bookCommentCopy1Dao struct {
	internalBookCommentCopy1Dao
}

var (
	// BookCommentCopy1 is globally public accessible object for table book_comment_copy1 operations.
	BookCommentCopy1 = bookCommentCopy1Dao{
		internal.NewBookCommentCopy1Dao(),
	}
)

// Fill with you ideas below.
