// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalBookCategoryDao is internal type for wrapping internal DAO implements.
type internalBookCategoryDao = *internal.BookCategoryDao

// bookCategoryDao is the data access object for table book_category.
// You can define custom methods on it to extend its functionality as you wish.
type bookCategoryDao struct {
	internalBookCategoryDao
}

var (
	// BookCategory is globally public accessible object for table book_category operations.
	BookCategory = bookCategoryDao{
		internal.NewBookCategoryDao(),
	}
)

// Fill with you ideas below.
