// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalBookInfoDao is internal type for wrapping internal DAO implements.
type internalBookInfoDao = *internal.BookInfoDao

// bookInfoDao is the data access object for table book_info.
// You can define custom methods on it to extend its functionality as you wish.
type bookInfoDao struct {
	internalBookInfoDao
}

var (
	// BookInfo is globally public accessible object for table book_info operations.
	BookInfo = bookInfoDao{
		internal.NewBookInfoDao(),
	}
)

// Fill with you ideas below.
