// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalHomeBookDao is internal type for wrapping internal DAO implements.
type internalHomeBookDao = *internal.HomeBookDao

// homeBookDao is the data access object for table home_book.
// You can define custom methods on it to extend its functionality as you wish.
type homeBookDao struct {
	internalHomeBookDao
}

var (
	// HomeBook is globally public accessible object for table home_book operations.
	HomeBook = homeBookDao{
		internal.NewHomeBookDao(),
	}
)

// Fill with you ideas below.
