// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalNewsInfoDao is internal type for wrapping internal DAO implements.
type internalNewsInfoDao = *internal.NewsInfoDao

// newsInfoDao is the data access object for table news_info.
// You can define custom methods on it to extend its functionality as you wish.
type newsInfoDao struct {
	internalNewsInfoDao
}

var (
	// NewsInfo is globally public accessible object for table news_info operations.
	NewsInfo = newsInfoDao{
		internal.NewNewsInfoDao(),
	}
)

// Fill with you ideas below.
