// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalNewsCategoryDao is internal type for wrapping internal DAO implements.
type internalNewsCategoryDao = *internal.NewsCategoryDao

// newsCategoryDao is the data access object for table news_category.
// You can define custom methods on it to extend its functionality as you wish.
type newsCategoryDao struct {
	internalNewsCategoryDao
}

var (
	// NewsCategory is globally public accessible object for table news_category operations.
	NewsCategory = newsCategoryDao{
		internal.NewNewsCategoryDao(),
	}
)

// Fill with you ideas below.
