// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalPayAlipayDao is internal type for wrapping internal DAO implements.
type internalPayAlipayDao = *internal.PayAlipayDao

// payAlipayDao is the data access object for table pay_alipay.
// You can define custom methods on it to extend its functionality as you wish.
type payAlipayDao struct {
	internalPayAlipayDao
}

var (
	// PayAlipay is globally public accessible object for table pay_alipay operations.
	PayAlipay = payAlipayDao{
		internal.NewPayAlipayDao(),
	}
)

// Fill with you ideas below.
