// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalPayWechatDao is internal type for wrapping internal DAO implements.
type internalPayWechatDao = *internal.PayWechatDao

// payWechatDao is the data access object for table pay_wechat.
// You can define custom methods on it to extend its functionality as you wish.
type payWechatDao struct {
	internalPayWechatDao
}

var (
	// PayWechat is globally public accessible object for table pay_wechat operations.
	PayWechat = payWechatDao{
		internal.NewPayWechatDao(),
	}
)

// Fill with you ideas below.
