// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalUserReadHistoryDao is internal type for wrapping internal DAO implements.
type internalUserReadHistoryDao = *internal.UserReadHistoryDao

// userReadHistoryDao is the data access object for table user_read_history.
// You can define custom methods on it to extend its functionality as you wish.
type userReadHistoryDao struct {
	internalUserReadHistoryDao
}

var (
	// UserReadHistory is globally public accessible object for table user_read_history operations.
	UserReadHistory = userReadHistoryDao{
		internal.NewUserReadHistoryDao(),
	}
)

// Fill with you ideas below.
