// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalUserBookshelfDao is internal type for wrapping internal DAO implements.
type internalUserBookshelfDao = *internal.UserBookshelfDao

// userBookshelfDao is the data access object for table user_bookshelf.
// You can define custom methods on it to extend its functionality as you wish.
type userBookshelfDao struct {
	internalUserBookshelfDao
}

var (
	// UserBookshelf is globally public accessible object for table user_bookshelf operations.
	UserBookshelf = userBookshelfDao{
		internal.NewUserBookshelfDao(),
	}
)

// Fill with you ideas below.
