// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalUserFeedbackDao is internal type for wrapping internal DAO implements.
type internalUserFeedbackDao = *internal.UserFeedbackDao

// userFeedbackDao is the data access object for table user_feedback.
// You can define custom methods on it to extend its functionality as you wish.
type userFeedbackDao struct {
	internalUserFeedbackDao
}

var (
	// UserFeedback is globally public accessible object for table user_feedback operations.
	UserFeedback = userFeedbackDao{
		internal.NewUserFeedbackDao(),
	}
)

// Fill with you ideas below.
