// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Literary_Snowlands/internal/dao/internal"
)

// internalUserCommentDao is internal type for wrapping internal DAO implements.
type internalUserCommentDao = *internal.UserCommentDao

// userCommentDao is the data access object for table user_comment.
// You can define custom methods on it to extend its functionality as you wish.
type userCommentDao struct {
	internalUserCommentDao
}

var (
	// UserComment is globally public accessible object for table user_comment operations.
	UserComment = userCommentDao{
		internal.NewUserCommentDao(),
	}
)

// Fill with you ideas below.
